var env = require('D:\\刻章软件\\rongcheng-miniprogram\\utils\\env-assessment.js');

function smartReplace(c){
  var D=new Date(),y=D.getFullYear(),m=String(D.getMonth()+1).padStart(2,'0'),d=String(D.getDate()).padStart(2,'0'),ds=y+'年'+m+'月'+d+'日',r=c;
  r=r.replace(/XXXX年XX月XX日/g,ds);
  r=r.replace(/本人XXX/g,'本人（示例：张三）');
  r=r.replace(/声明单位：XXX有限公司/g,'声明单位：（示例：XX有限公司）');
  ['声明人','致歉人','联系人','法定代表人','债权申报联系人','申请人','被申请人','当事人','负责人','声明人（单位）','新郎','新娘','学生','学子','祝福人','祝福你的人','永远的朋友','家人','家长','出借人','借款人','股东','权利人'].forEach(function(f){r=r.replace(new RegExp(f+'：XXX','g'),f+'：（示例：张三）');});
  r=r.replace(/XXX（[^）]*）/g,'（示例：张三）');
  r=r.replace(/XXX (?=先生|女士|老师|小姐|公子|寿星|喜结连理)/g,'张三 ');
  r=r.replace(/致我最好的朋友 XXX/g,'致我最好的朋友 张三');
  r=r.replace(/(亲爱的|敬爱的) XXX/g,'$1 张三');
  r=r.replace(/致 XXX/g,'致 张三');
  r=r.replace(/致我亲爱的宝宝 XXX/g,'致我亲爱的宝宝 张三');
  r=r.replace(/永远爱你的：XXX/g,'永远爱你的：（示例：张三）');
  r=r.replace(/TO: XXX/g,'TO: 张三');
  r=r.replace(/FROM: XXX/g,'FROM: 张三');
  r=r.replace(/您的孩子：XXX/g,'您的孩子：（示例：张三）');
  r=r.replace(/XXX  XXX(\s*XXX)*/g,function(m){return m.replace(/XXX/g,'（示例：张三）');});
  ['身份证号','注册号','执业证号','许可证编号','许可证号','保单号','机构编码','账号'].forEach(function(f){r=r.replace(new RegExp(f+'：X{8,}','g'),f+'：（请填写完整信息）');});
  ['票据号码','证号','编号','权证编号','证书编号','设备编号','证件编号','合同编号','备案/登记编号','许可证号/证书号','证件号码'].forEach(function(f){
    r=r.replace(new RegExp(f+'：X{4,}','g'),f+'：__NUMCODE__');
    r=r.replace(new RegExp(f+'：XXX','g'),f+'：（示例：12345678）');
  });
  r=r.replace(/公告单位：XXX/g,'公告单位：（示例：XX有限公司）');
  r=r.replace(/通知人：XXX/g,'通知人：（示例：张三）');
  r=r.replace(/致：XXX/g,'致：（示例：张三）');
  r=r.replace(/联系地址：XXXX/g,'联系地址：（示例：XX市XX区XX路XX号）');
  r=r.replace(/受让人：XXX/g,'受让人：（示例：张三）');
  r=r.replace(/受让方：XXX/g,'受让方：（示例：张三）');
  r=r.replace(/转让人：XXX/g,'转让人：（示例：张三）');
  r=r.replace(/原债权人：XXX/g,'原债权人：（示例：张三）');
  r=r.replace(/名称：XXX/g,'名称：（示例：XX公司）');
  r=r.replace(/贷款机构：XXX/g,'贷款机构：（示例：XX银行）');
  r=r.replace(/授权代表：XXX/g,'授权代表：（示例：张三）');
  r=r.replace(/保险公司：XXX/g,'保险公司：（示例：XX保险公司）');
  r=r.replace(/投保了XXX保险/g,'投保了（示例：XX保险）');
  r=r.replace(/XXX保险/g,'（示例：XX保险）');
  r=r.replace(/（XXXX）/g,'（（示例：2026））');
  r=r.replace(/〔XXXX〕/g,'〔2026〕');
  r=r.replace(/([民刑]初)XXX号/g,'$1（示例：1234）号');
  r=r.replace(/XXXX-XXXXXXXX/g,'（示例：0755-12345678）');
  r=r.replace(/XXXX有限公司/g,'（示例：XX公司）有限公司');
  r=r.replace(/XXX保险公司/g,'（示例：XX保险公司）');
  r=r.replace(/XXX物业管理有限公司/g,'（示例：XX物业管理有限公司）');
  ['被告','债务人','借款人','出借人','被执行人','被征收人','失踪人','担保人','债权人','遗赠人','受遗赠人','抚养人','收养人','申请人','被申请人','声明人','当事人','通知人','公告人','被保险人','主要负责人','权利人','股东','受让人','转让人'].forEach(function(role){r=r.replace(new RegExp(role+'XXX(?!（)','g'),role+'（示例：张三）');});
  r=r.replace(/XXX诉/g,'（示例：张三）诉');
  r=r.replace(/XXX与/g,'（示例：张三）与');
  r=r.replace(/就XXX/g,'就（示例：XX）');
  r=r.replace(/XXX罪/g,'（示例：XX罪）');
  r=r.replace(/XXX事项/g,'（示例：XX事项）');
  r=r.replace(/XXX情形/g,'（示例：XX情形）');
  r=r.replace(/XXX争议/g,'（示例：XX争议）');
  r=r.replace(/XXX内容/g,'（示例：XX内容）');
  r=r.replace(/XXX名称/g,'（示例：XX名称）');
  r=r.replace(/XXX概要/g,'（示例：XX概要）');
  r=r.replace(/案由：XXX/g,'案由：（示例：XX纠纷）');
  r=r.replace(/原规划条件：XXX/g,'原规划条件：（示例：XX）');
  r=r.replace(/变更后规划条件：XXX/g,'变更后规划条件：（示例：XX）');
  r=r.replace(/地址：XXXX/g,'地址：（示例：XX市XX区XX路XX号）');
  r=r.replace(/户名：XXXX/g,'户名：（示例：XX银行）');
  r=r.replace(/账号：X{8,20}/g,'账号：（示例：6222****1234）');
  r=r.replace(/统一社会信用代码：X{8,}/g,'统一社会信用代码：__CREDIT_CODE__');
  r=r.replace(/统一社会信用代码：\d{2}X{6,}/g,'统一社会信用代码：__CREDIT_CODE__');
  r=r.replace(/XXXX(劳人仲|合同仲|民仲)/g,'（示例：2026）$1');
  r=r.replace(/X{4,8}字第/g,'（示例：2026）字第');
  r=r.replace(/XXX律师事务所/g,'（示例：XX律师事务所）');
  r=r.replace(/XXX律师/g,'（示例：XX律师）');
  r=r.replace(/XXX证券期货有限公司/g,'（示例：XX证券期货有限公司）');
  r=r.replace(/XXX出版社/g,'（示例：XX出版社）');
  r=r.replace(/车牌号：X{6,8}/g,'车牌号：（示例：粤B12345）');
  r=r.replace(/票号：X{6,10}/g,'票号：（示例：12345678）');
  r=r.replace(/存放编号：X{6,10}/g,'存放编号：（示例：12345678）');
  r=r.replace(/机构名称：XXX/g,'机构名称：（示例：XX证券）');
  r=r.replace(/ISBN：X{13,}/g,'ISBN：（示例：978-7-XXXX-XXXX-X）');
  r=r.replace(/XXX路/g,'（示例：XX）路');
  r=r.replace(/XXX号/g,'（示例：XX）号');
  r=r.replace(/XXX室/g,'（示例：XX）室');
  r=r.replace(/XXX平方米/g,'（示例：XX）平方米');
  r=r.replace(/提存原因：XXX/g,'提存原因：（示例：XX）');
  r=r.replace(/车型：XXX/g,'车型：（示例：XX牌XX型）');
  r=r.replace(/身高：XXXcm/g,'身高：（示例：170）cm');
  r=r.replace(/体貌特征：XXX/g,'体貌特征：（示例：XX）');
  r=r.replace(/(起火|死亡)原因为XXX/g,'$1原因为（示例：XX）');
  r=r.replace(/授权范围：XXX/g,'授权范围：（示例：XX）');
  r=r.replace(/办理XXX案件/g,'办理（示例：XX）案件');
  r=r.replace(/XXXX（事项/g,'（示例：XX事项');
  r=r.replace(/XXXX（行为/g,'（示例：XX行为');
  r=r.replace(/XXXX（相关/g,'（示例：XX相关');
  r=r.replace(/XXX公司(?!\d)/g,'（示例：XX公司）');
  r=r.replace(/XXXX公司/g,'（示例：XX公司');
  r=r.replace(/（示例：XX公司有限公司/g,'（示例：XX公司）有限公司');
  r=r.replace(/（示例：XX公司集团/g,'（示例：XX集团）');
  // 环评专项（必须在 XXXX(?!\d) 之前）
  r=r.replace(/XXXX@[^\\s，,。.！!？?\n]+/g,'（示例：test@example.com）');
  r=r.replace(/XXXX万元/g,'（示例：100）万元');
  r=r.replace(/XXXX千瓦时/g,'（示例：100）千瓦时');
  r=r.replace(/XXXX吨\/年/g,'（示例：10）吨/年');
  r=r.replace(/XXXX个/g,'（示例：2）个');
  r=r.replace(/XXXX平方米/g,'（示例：1000）平方米');
  r=r.replace(/XXXXXX(?=[）\\)\\s]|$)/g,'（示例：518000）');
  r=r.replace(/废气：XXXXXXXX/g,'废气：（请填写具体措施）');
  r=r.replace(/废水：XXXXXXXX/g,'废水：（请填写具体措施）');
  r=r.replace(/噪声：XXXXXXXX/g,'噪声：（请填写具体措施）');
  r=r.replace(/固废：XXXXXXXX/g,'固废：（请填写具体措施）');
  r=r.replace(/噪声防治设施：XXXXXXXX/g,'噪声防治设施：（请填写具体内容）');
  r=r.replace(/固体废物污染防治设施：XXXXXXXX/g,'固体废物污染防治设施：（请填写具体内容）');
  r=r.replace(/排放口数量及分布：XXXXXXXX/g,'排放口数量及分布：（请填写具体数量）');
  r=r.replace(/主要污染防治设施：XXXXXXXX/g,'主要污染防治设施：（请填写具体内容）');
  r=r.replace(/查阅方式和途径：XXXXXXXX/g,'查阅方式和途径：（请填写查阅方式）');
  r=r.replace(/验收报告及验收意见查阅方式：XXXXXXXX/g,'验收报告及验收意见查阅方式：（请填写查阅方式）');
  r=r.replace(/联系方式：XXXXXXXX/g,'联系方式：（请填写联系方式）');
  r=r.replace(/联系人及联系方式：XXXXXXXX/g,'联系人及联系方式：（请填写联系方式）');
  r=r.replace(/验收调查单位：XXXXXXXX/g,'验收调查单位：（请填写单位名称）');
  r=r.replace(/验收监测单位：XXXXXXXX/g,'验收监测单位：（请填写单位名称）');
  r=r.replace(/主要建设内容：XXXXXXXX/g,'主要建设内容：（请填写具体建设内容）');
  r=r.replace(/许可排放量及排放标准：XXXXXXXX/g,'许可排放量及排放标准：（请填写具体数值）');
  r=r.replace(/年排放量：XXXXXXXX/g,'年排放量：（请填写具体排放量）');
  r=r.replace(/XXXXXX方案（X项）：XXXXXXXX/g,'（示例：5项）方案（示例：3项）：（请填写具体方案）');
  r=r.replace(/已完成.*?方案（X项）：XXXXXXXX/g,'已完成方案（示例：5项）：（请填写具体方案）');
  r=r.replace(/已实施.*?方案（X项）：XXXXXXXX/g,'已实施方案（示例：3项）：（请填写具体方案）');
  r=r.replace(/下一步清洁生产计划：XXXXXXXX/g,'下一步清洁生产计划：（请填写计划内容）');
  r=r.replace(/应急预案备案编号：XXXXXXXX/g,'应急预案备案编号：（请填写备案编号）');
  r=r.replace(/备案编号：XXXXXXXX/g,'备案编号：（请填写备案编号）');
  r=r.replace(/风险等级：XXXXXXXX/g,'风险等级：（请填写风险等级）');
  r=r.replace(/主要风险源：XXXXXXXX/g,'主要风险源：（请填写具体风险源）');
  r=r.replace(/可能影响：XXXXXXXX/g,'可能影响：（请填写可能影响）');
  r=r.replace(/防范措施：XXXXXXXX/g,'防范措施：（请填写防范措施）');
  r=r.replace(/许可证编号：XXXXXXXX/g,'许可证编号：（示例：12345678）');
  r=r.replace(/变更前主要内容：XXXXXXXX/g,'变更前主要内容：（请填写具体内容）');
  r=r.replace(/变更后主要内容：XXXXXXXX/g,'变更后主要内容：（请填写具体内容）');
  r=r.replace(/变更原因：XXXXXXXX/g,'变更原因：（请填写变更原因）');
  r=r.replace(/注销原因：XXXXXXXX/g,'注销原因：（请填写注销原因）');
  r=r.replace(/延续申请理由：XXXXXXXX/g,'延续申请理由：（请填写理由）');
  r=r.replace(/场地原使用情况：XXXXXXXX/g,'场地原使用情况：（请填写场地历史用途）');
  r=r.replace(/污染物识别结果：XXXXXXXX/g,'污染物识别结果：（请填写识别结果）');
  r=r.replace(/土壤检测结果：XXXXXXXX/g,'土壤检测结果：（请填写检测结果）');
  r=r.replace(/地下水检测结果：XXXXXXXX/g,'地下水检测结果：（请填写检测结果）');
  r=r.replace(/许可经营危险废物类别及规模：XXXXXXXX/g,'许可经营危险废物类别及规模：（请填写具体类别）');
  r=r.replace(/许可范围：XXXXXXXX/g,'许可范围：（请填写许可范围）');
  r=r.replace(/行业类别：XXXX/g,'行业类别：（示例：制造业）');
  r=r.replace(/变更原因：XXXXXXXXX（如：.*?）/g,'变更原因：（示例：生产规模扩大）（如：增加生产线）');
  r=r.replace(/X{15,}/g,'（请填写完整信息）');
  r=r.replace(/XXXX(?!\d)/g,'（示例：138****5678）');
  r=r.replace(/XXX(?!\d)/g,'（示例：110101199001011234）');
  r=r.replace(/统一社会信用代码：__CREDIT_CODE__/g,'统一社会信用代码：（示例：91XXXXXXXXXX）');
  r=r.replace(/__NUMCODE__/g,'（示例：91XXXXXXXXXX）');
  return r;
}

var pass=0,fail=0;
env.categories.forEach(function(cat){
  cat.docs.forEach(function(doc){
    var r=smartReplace(env.generateContent(doc.name));
    var clean=r.replace(/（示例：[^）]+）/g,'_').replace(/（请填写[^）]+）/g,'_').replace(/（日期：[^）]+）/g,'_');
    var bad=[];
    var m;
    var rx1=/[^\u300a-\u300b\u3010-\u3011\uFF08-\uFF09]XXX(?!X)(?![\u4e00-\u9fa5])/g;
    while(m=rx1.exec(clean)) if(m[0][0]!=='（'&&m[0][0]!=='【') bad.push(m[0]);
    var rx2=/[^\u300a-\u300b\u3010-\u3011]XXXX(?![\d\u4e00-\u9fa5])/g;
    while(m=rx2.exec(clean)) bad.push(m[0]);
    if(bad.length){fail++;console.log('FAIL '+doc.name+': '+bad.slice(0,5).join(', '));}
    else{pass++;console.log('OK '+doc.name);}
  });
});
console.log('\n'+pass+'/'+(pass+fail)+' passed\n--- 全部输出 ---');
env.categories.forEach(function(cat){
  console.log('\n【'+cat.name+'】');
  cat.docs.forEach(function(doc){
    console.log('\n== '+doc.name+' ==\n'+smartReplace(env.generateContent(doc.name)));
  });
});
