/**
 * 个人证件登报模板配置
 * 274项去重后7大业务分类，每项含 emoji 图标
 */

/**
 * 根据证件名称和分类生成登报模板内容
 */
function generateContent(name, categoryName) {
  const templates = {
    '职业资格与执业证件': `${name}遗失声明\n\n本人XXX不慎遗失${name}，证书编号：XXX，特此声明作废。\n\n声明人：XXX\n联系电话：XXXX\n日期：XXXX年XX月XX日`,
    '医疗健康类': `${name}遗失声明\n\n本人XXX不慎遗失${name}，编号：XXX，特此声明作废。\n\n声明人：XXX\n联系电话：XXXX\n日期：XXXX年XX月XX日`,
    '合同协议与法律文书': `${name}遗失声明\n\n本人XXX不慎遗失${name}，编号：XXX，特此声明作废。\n\n声明人：XXX\n联系电话：XXXX\n日期：XXXX年XX月XX日`,
    '房产与土地相关证件单据': `${name}遗失声明\n\n本人XXX不慎遗失${name}，权证编号：XXX，特此声明作废。\n\n声明人：XXX\n联系电话：XXXX\n日期：XXXX年XX月XX日`,
    '金融财税与票据': `${name}遗失声明\n\n本人XXX不慎遗失${name}，票据编号：XXX，特此声明作废。\n\n声明人：XXX\n联系电话：XXXX\n日期：XXXX年XX月XX日`,
    '交通与运输相关证件': `${name}遗失声明\n\n本人XXX不慎遗失${name}，证号：XXX，特此声明作废。\n\n声明人：XXX\n联系电话：XXXX\n日期：XXXX年XX月XX日`,
    '企业证件': `${name}遗失声明\n\n本公司不慎遗失${name}，编号：XXX，特此声明作废。\n\n声明单位：XXX\n联系电话：XXXX\n日期：XXXX年XX月XX日`
  };
  return templates[categoryName] || `${name}遗失声明\n\n本人XXX不慎遗失${name}，编号：XXX，特此声明作废。\n\n声明人：XXX\n联系电话：XXXX\n日期：XXXX年XX月XX日`;
}

module.exports = {
  generateContent,
  categories: [
    {
      name: '职业资格与执业证件',
      desc: '职业资格证/执业证/工作证/培训合格证',
      color: '#F5222D',
      iconSvg: '/assets/icons/icon-doc-09-generic.svg',
      total: 114,
      docs: [
        { name: '注册消防工程师资格证书', icon: '🔥' },
        { name: '一级注册消防工程师', icon: '🔥' },
        { name: '二级注册消防工程师', icon: '🔥' },
        { name: '消防设施操作员', icon: '🔥' },
        { name: '一级建造师执业资格证书', icon: '🏗️' },
        { name: '二级建造师执业资格证书', icon: '🏗️' },
        { name: '一级造价工程师', icon: '🏗️' },
        { name: '二级造价工程师', icon: '🏗️' },
        { name: '一级注册建筑师', icon: '🏗️' },
        { name: '二级注册建筑师', icon: '🏗️' },
        { name: '注册结构工程师', icon: '🏗️' },
        { name: '注册土木工程师', icon: '🏗️' },
        { name: '注册公用设备工程师', icon: '🏗️' },
        { name: '注册电气工程师', icon: '🏗️' },
        { name: '注册城乡规划师', icon: '🔖' },
        { name: '注册监理工程师', icon: '🏗️' },
        { name: '注册安全工程师', icon: '🔥' },
        { name: '注册测绘师', icon: '🏗️' },
        { name: '市政道路工程师证', icon: '🏗️' },
        { name: '注册环保工程师', icon: '🏗️' },
        { name: '注册会计师证书', icon: '📊' },
        { name: '注册税务师', icon: '💳' },
        { name: '注册资产评估师', icon: '🔖' },
        { name: '初级会计师', icon: '📊' },
        { name: '中级会计师', icon: '📊' },
        { name: '高级会计师', icon: '📊' },
        { name: '审计师资格证书', icon: '📊' },
        { name: '统计师资格证书', icon: '📊' },
        { name: '经济师资格证书', icon: '📊' },
        { name: '律师执业证书', icon: '⚖️' },
        { name: '法律职业资格证书', icon: '⚖️' },
        { name: '公职律师工作证', icon: '⚖️' },
        { name: '公司律师工作证', icon: '⚖️' },
        { name: '公证员执业证书', icon: '⚖️' },
        { name: '基层法律服务工作者执业证', icon: '⚖️' },
        { name: '法律顾问资格证', icon: '⚖️' },
        { name: '人民调解员证', icon: '⚖️' },
        { name: '教师资格证书', icon: '📚' },
        { name: '幼儿园教师资格证', icon: '📚' },
        { name: '小学教师资格证', icon: '📚' },
        { name: '中学教师资格证', icon: '📚' },
        { name: '高等学校教师资格证', icon: '📚' },
        { name: '中等职业学校教师资格证', icon: '📚' },
        { name: '教师荣誉证书', icon: '📚' },
        { name: '执业医师证', icon: '🏥' },
        { name: '执业助理医师证', icon: '🏥' },
        { name: '护士执业证', icon: '🏥' },
        { name: '执业药师证', icon: '🏥' },
        { name: '执业中药师证', icon: '🏥' },
        { name: '执业西药师证', icon: '🏥' },
        { name: '放射防护知识培训合格证书', icon: '☢️' },
        { name: '道路运输从业人员从业资格证', icon: '🚗' },
        { name: '巡游出租汽车驾驶员证', icon: '🚕' },
        { name: '网络预约出租汽车驾驶员证', icon: '🚕' },
        { name: '导游标识卡', icon: '🗺️' },
        { name: '导游资格证书', icon: '🗺️' },
        { name: '中级导游证', icon: '🗺️' },
        { name: '高级导游证', icon: '🗺️' },
        { name: '特种作业操作证', icon: '🔖' },
        { name: '高处作业特种作业操作证', icon: '🔖' },
        { name: '焊接与热切割作业证', icon: '⚡' },
        { name: '电工进网作业许可证', icon: '⚡' },
        { name: '压力容器证', icon: '⚡' },
        { name: '特种设备作业人员证', icon: '⚡' },
        { name: '电梯作业证', icon: '⚡' },
        { name: '起重机械作业证', icon: '⚡' },
        { name: '锅炉作业证', icon: '⚡' },
        { name: '压力管道作业证', icon: '🔖' },
        { name: '金属非金属矿山安全作业证', icon: '🔥' },
        { name: '危险化学品安全作业证', icon: '🔥' },
        { name: '烟花爆竹安全作业证', icon: '🔥' },
        { name: '矿业权评估师', icon: '🔖' },
        { name: '爆破作业人员许可证', icon: '💣' },
        { name: '安全生产知识和管理能力考核合格证', icon: '🔥' },
        { name: '房地产估价师', icon: '🏠' },
        { name: '房地产经纪人', icon: '🏠' },
        { name: '土地估价师', icon: '🏠' },
        { name: '土地登记代理人', icon: '🏠' },
        { name: '资产评估师', icon: '🔖' },
        { name: '价格鉴证师', icon: '🔖' },
        { name: '专利代理师资格证书', icon: '💡' },
        { name: '商标代理人', icon: '💡' },
        { name: '版权代理人', icon: '💡' },
        { name: '社会工作者职业水平证书', icon: '🔖' },
        { name: '养老护理员', icon: '🏥' },
        { name: '家政服务员', icon: '👨‍👩‍👧' },
        { name: '育婴员', icon: '👨‍👩‍👧' },
        { name: '保育员', icon: '👨‍👩‍👧' },
        { name: '健康管理师', icon: '🏥' },
        { name: '公共营养师', icon: '🏥' },
        { name: '心理咨询师', icon: '🧠' },
        { name: '公路检测员证', icon: '🛣️' },
        { name: '公路水运工程试验检测师', icon: '🏗️' },
        { name: '水运工程监理工程师', icon: '🏗️' },
        { name: '水利工程质量检测员', icon: '🏗️' },
        { name: '水利造价工程师', icon: '🏗️' },
        { name: '水利水电工程注册土木工程师', icon: '🏗️' },
        { name: '注册设备监理师', icon: '🏗️' },
        { name: '注册验船师', icon: '🔖' },
        { name: '注册计量师', icon: '🔖' },
        { name: '标准化工程师', icon: '🏗️' },
        { name: '质量管理体系审核员', icon: '🔖' },
        { name: '环境管理体系审核员', icon: '🌿' },
        { name: '职业健康安全管理体系审核员', icon: '🏥' },
        { name: '食品检验工', icon: '🥗' },
        { name: '农产品食品检验员', icon: '🥗' },
        { name: '机动车检测维修工程师', icon: '🏗️' },
        { name: '机动车检测维修士', icon: '🚗' },
        { name: '公路工程造价工程师', icon: '🏗️' },
        { name: '水利工程监理工程师', icon: '🏗️' },
        { name: '文物保护工程专业人员', icon: '🏗️' },
        { name: '勘察设计注册工程师', icon: '🏗️' },
        { name: '信息系统项目管理师', icon: '💻' },
        { name: '系统集成项目管理工程师', icon: '🏗️' },
      ]
    },
    {
      name: '医疗健康类',
      desc: '出生证明/体检报告/健康证明/诊断证明书',
      color: '#EB2F96',
      iconSvg: '/assets/icons/icon-doc-04-generic.svg',
      total: 7,
      docs: [
        { name: '疾病证明书', icon: '📋' },
        { name: '出生医学证明', icon: '📋' },
        { name: '死亡医学证明', icon: '📋' },
        { name: '体检报告', icon: '📋' },
        { name: '健康证明', icon: '🏥' },
        { name: '医师定期考核合格证明', icon: '🏥' },
        { name: '职业病诊断证明书', icon: '🔖' },
      ]
    },
    {
      name: '合同协议与法律文书',
      desc: '合同/协议/法律文书/委托书/公证书',
      color: '#52C41A',
      iconSvg: '/assets/icons/icon-doc-03-generic.svg',
      total: 25,
      docs: [
        { name: '委托代理合同书', icon: '📝' },
        { name: '诚意金协议书', icon: '📝' },
        { name: '驾校学车合同', icon: '📝' },
        { name: '委培书', icon: '🔖' },
        { name: '销售送货单', icon: '🔖' },
        { name: '诉责险保险单', icon: '🛡️' },
        { name: '保函', icon: '📝' },
        { name: '证据先行登记保存通知书', icon: '🔖' },
        { name: '租赁保证金单据', icon: '📝' },
        { name: '公租房保证金收据', icon: '💳' },
        { name: '上房通知单', icon: '🔖' },
        { name: '预售备案登记表', icon: '🔖' },
        { name: '劳动合同', icon: '📝' },
        { name: '劳务派遣合同', icon: '📝' },
        { name: '保密协议', icon: '📝' },
        { name: '竞业限制协议', icon: '📝' },
        { name: '采购合同', icon: '📝' },
        { name: '购销合同', icon: '📝' },
        { name: '借款合同', icon: '📝' },
        { name: '担保合同', icon: '📝' },
        { name: '抵押合同', icon: '📝' },
        { name: '租赁合同', icon: '📝' },
        { name: '承揽合同', icon: '📝' },
        { name: '建设工程施工合同', icon: '🏗️' },
        { name: '技术服务合同', icon: '📝' },
      ]
    },
    {
      name: '房产与土地相关证件单据',
      desc: '房产证/土地证/不动产权证/安置协议',
      color: '#FA8C16',
      iconSvg: '/assets/icons/icon-doc-07-generic.svg',
      total: 34,
      docs: [
        { name: '不动产权证书', icon: '🏡' },
        { name: '房屋所有权证', icon: '🏡' },
        { name: '共有权证', icon: '🔖' },
        { name: '他项权证', icon: '🔖' },
        { name: '房屋他项权证', icon: '🏡' },
        { name: '国有土地使用证', icon: '🏠' },
        { name: '集体土地使用证', icon: '🏠' },
        { name: '土地确权登记证', icon: '🏠' },
        { name: '房屋安置结算表', icon: '🏡' },
        { name: '土地安置结算卡', icon: '🏠' },
        { name: '房屋补差款票据', icon: '💳' },
        { name: '房屋承租本', icon: '🏡' },
        { name: '棚户区改造项目安置房选房确认单', icon: '💻' },
        { name: '房屋征收补偿安置协议', icon: '📝' },
        { name: '征地补偿安置方案', icon: '🔖' },
        { name: '失地农民证明', icon: '🔖' },
        { name: '房屋买卖契约', icon: '🏡' },
        { name: '商品房买卖合同', icon: '📝' },
        { name: '存量房买卖合同', icon: '📝' },
        { name: '房地产抵押合同', icon: '🏠' },
        { name: '房屋租赁备案证明', icon: '📝' },
        { name: '房屋安全鉴定报告', icon: '🏡' },
        { name: '房产分户图', icon: '🔖' },
        { name: '不动产登记证明', icon: '🏡' },
        { name: '建设用地规划许可证', icon: '🔖' },
        { name: '建设工程规划许可证', icon: '🏗️' },
        { name: '建筑工程施工许可证', icon: '🏗️' },
        { name: '竣工验收备案表', icon: '🔖' },
        { name: '住宅质量保证书', icon: '🔖' },
        { name: '住宅使用说明书', icon: '🔖' },
        { name: '投资登记本', icon: '💰' },
        { name: '房屋维修基金缴纳凭证', icon: '🏡' },
        { name: '契税完税证明', icon: '🧾' },
        { name: '购房资格核验结果', icon: '🔖' },
      ]
    },
    {
      name: '金融财税与票据',
      desc: '发票/收据/税票/保险单/保证金收据',
      color: '#5B6FE8',
      iconSvg: '/assets/icons/icon-doc-05-generic.svg',
      total: 28,
      docs: [
        { name: '增值税普通发票', icon: '💳' },
        { name: '增值税专用发票', icon: '💳' },
        { name: '电子发票', icon: '💳' },
        { name: '定额发票', icon: '💳' },
        { name: '机动车销售统一发票', icon: '🚗' },
        { name: '二手车销售统一发票', icon: '💳' },
        { name: '非税收入统一票据', icon: '💳' },
        { name: '非税收入电子交款书', icon: '🧾' },
        { name: '税收缴款书', icon: '🧾' },
        { name: '个人所得税纳税记录', icon: '🧾' },
        { name: '完税证明', icon: '🧾' },
        { name: '社会保险费缴费证明', icon: '🛡️' },
        { name: '医疗保险缴费证明', icon: '🏥' },
        { name: '住房公积金缴存证明', icon: '🧾' },
        { name: '银行回单', icon: '💳' },
        { name: '银行流水', icon: '💳' },
        { name: '银行存款证明', icon: '💳' },
        { name: '个人信用报告', icon: '⭐' },
        { name: '企业信用报告', icon: '⭐' },
        { name: '保险单', icon: '🛡️' },
        { name: '保险批单', icon: '🛡️' },
        { name: '保险发票', icon: '🛡️' },
        { name: '保单贷款凭证', icon: '💰' },
        { name: '保证金收据', icon: '💳' },
        { name: '支票', icon: '💳' },
        { name: '汇票', icon: '💳' },
        { name: '本票', icon: '💳' },
        { name: '收据', icon: '💳' },
      ]
    },
    {
      name: '交通与运输相关证件',
      desc: '驾驶证/行驶证/船舶证书/运输单据',
      color: '#9BA8FF',
      iconSvg: '/assets/icons/icon-doc-11-generic.svg',
      total: 16,
      docs: [
        { name: '驾驶证', icon: '🚗' },
        { name: '行驶证', icon: '🚗' },
        { name: '机动车登记证书', icon: '🚗' },
        { name: '机动车检验合格标志', icon: '🚗' },
        { name: '道路运输证', icon: '🚗' },
        { name: '道路运输经营许可证', icon: '🚗' },
        { name: '道路危险货物运输许可证', icon: '🚗' },
        { name: '网络预约出租汽车运输证', icon: '🚗' },
        { name: '巡游出租汽车经营许可证', icon: '🚕' },
        { name: '船舶所有权登记证书', icon: '🚢' },
        { name: '船舶国籍证书', icon: '🚢' },
        { name: '渔业船舶国籍证书', icon: '🚢' },
        { name: '捕捞辅助船许可证', icon: '🚢' },
        { name: '船舶检验证书', icon: '🚢' },
        { name: '海关货物进口证明书', icon: '🌐' },
        { name: '随车检验单', icon: '🔖' },
      ]
    },
  {
      name: '企业证件',
      desc: '营业执照/资质证书/经营许可证等企业证件遗失声明',
      color: '#1890FF',
      iconSvg: '/assets/icons/icon-doc-02-generic.svg',
      total: 50,
      docs: [
        { name: '营业执照（正本）', icon: '🏢' },
        { name: '营业执照（副本）', icon: '🏢' },
        { name: '企业法人营业执照', icon: '🏢' },
        { name: '个体工商户营业执照', icon: '🏢' },
        { name: '组织机构代码证', icon: '💼' },
        { name: '税务登记证（国税）', icon: '📄' },
        { name: '税务登记证（地税）', icon: '📄' },
        { name: '银行开户许可证', icon: '📜' },
        { name: '社会保险登记证', icon: '📄' },
        { name: '住房公积金登记证', icon: '📄' },
        { name: '统计登记证（统计证）', icon: '📄' },
        { name: '消防验收合格证', icon: '📜' },
        { name: '食品经营许可证', icon: '📜' },
        { name: '食品生产许可证', icon: '📜' },
        { name: '卫生许可证', icon: '📜' },
        { name: '公共场所卫生许可证', icon: '📜' },
        { name: '排污许可证', icon: '📜' },
        { name: '安全生产许可证', icon: '📜' },
        { name: '印刷经营许可证', icon: '📜' },
        { name: '药品经营许可证', icon: '📜' },
        { name: '医疗器械经营许可证', icon: '📜' },
        { name: '医疗器械生产许可证', icon: '📜' },
        { name: '药品生产许可证', icon: '📜' },
        { name: 'GMP认证证书', icon: '🏅' },
        { name: 'GSP认证证书', icon: '🏅' },
        { name: 'ISO9001质量管理体系认证证书', icon: '🏅' },
        { name: 'ISO14001环境管理体系认证证书', icon: '🏅' },
        { name: '职业健康安全管理体系认证证书', icon: '🏅' },
        { name: 'CE认证证书', icon: '🏅' },
        { name: 'FCC认证证书', icon: '🏅' },
        { name: 'RoHS认证证书', icon: '🏅' },
        { name: '商标注册证', icon: '📄' },
        { name: '专利证书', icon: '💡' },
        { name: '软件著作权登记证书', icon: '📄' },
        { name: 'ICP增值电信业务经营许可证', icon: '📜' },
        { name: 'EDI在线数据处理许可证', icon: '📜' },
        { name: '网络文化经营许可证', icon: '📜' },
        { name: '广播电视节目制作经营许可证', icon: '📜' },
        { name: '办学许可证', icon: '📜' },
        { name: '医疗机构执业许可证', icon: '📜' },
        { name: '民办非企业单位登记证书', icon: '📄' },
        { name: '社会团体法人登记证书', icon: '📄' },
        { name: '基金会法人登记证书', icon: '📄' },
        { name: '会计师事务所执业证书', icon: '💼' },
        { name: '律师事务所执业许可证', icon: '📜' },
        { name: '建筑业企业资质证书', icon: '💼' },
        { name: '房地产开发资质证书', icon: '💼' },
        { name: '物业服务企业资质证书', icon: '💼' },
        { name: '特种设备生产许可证', icon: '📜' },
        { name: '承装（修、试）电力设施许可证', icon: '📜' }
      ]
    }
  ],

  getTotalCount() {
    return this.categories.reduce((sum, cat) => sum + cat.docs.length, 0);
  }
};
